#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

echo "=== Running Repo Tests ==="
exec < /dev/tty
declare failcount=0

for file in ./tests/*
do
	echo "Running test file $file..."
	bash $file
	ec=$?
	if [ $ec != "0" ]; then
		echo "Test failed: $file"
		failcount=$((failcount + 1))
	fi
done

if [[ $failcount != "0" ]]; then
	echo "Do you want to continue with the commit? Y/N"
	read input
	if [[ $input != "Y" ]]; then
		echo "Did not commit."
		exit 1
	fi
fi

echo "All tests pass, proceeding with commit."
echo "==========================";


