#!/bin/sh
#
# To enable this hook, rename this file to "pre-commit".
#
# This hook will execute all scripts in a top level
# tests directory before a commit and warn the user
# if any are failing.
#

echo "=== Running Repo Tests ==="

# Get standard input from terminal
exec < /dev/tty
declare failcount=0

# Run each script in tests folder and log any failures
for file in ./tests/*
do
	echo "Running test file $file..."
	bash $file
	ec=$?
	if [ $ec != "0" ]; then
		echo "Test failed: $file"
		failcount=$((failcount + 1))
	fi
done

# If there were any failures, inform the user and ask if
# they still want to proceed with the commit
if [[ $failcount != "0" ]]; then
	echo "Number of failures: $failcount"
	echo "Do you want to continue with the commit? Y/N"
	read input
	if [[ $input != "Y" ]]; then
		echo "Did not commit."
		exit 1
	fi
else
	echo "All tests pass, proceeding with commit."
fi

echo "==========================";	


